// This file was not generated by a tool.
#include "common.h"
#include "../gfx/titleScreen.h"
#include "../gfx/bg.h"
#include "../gfx/gfx.h"
#include "../gfx/bossgfx.h"
#include "../gfx/bossWarning.h"

unsigned short *image_entries[NB_IMAGES];
unsigned short *bossImage_entries[NB_BOSS_IMAGES];

void buildGameLUTs()
{
	// Base images
	image_entries[image_LUT_player_ship_light] = image_player_ship_light;
	image_entries[image_LUT_player_ship_shadow] = image_player_ship_shadow;
	image_entries[image_LUT_player_ship_polarityswitch_0_light] = image_player_ship_polarityswitch_0_light;
	image_entries[image_LUT_player_ship_polarityswitch_0_shadow] = image_player_ship_polarityswitch_0_shadow;
	image_entries[image_LUT_player_ship_polarityswitch_1_light] = image_player_ship_polarityswitch_1_light;
	image_entries[image_LUT_player_ship_polarityswitch_1_shadow] = image_player_ship_polarityswitch_1_shadow;
	image_entries[image_LUT_player_ship_invincible_light] = image_player_ship_invincible_light;
	image_entries[image_LUT_player_ship_invincible_shadow] = image_player_ship_invincible_shadow;
	image_entries[image_LUT_player_homing_bullet_light_0] = image_player_homing_bullet_light_0;
	image_entries[image_LUT_player_homing_bullet_light_1] = image_player_homing_bullet_light_1;
	image_entries[image_LUT_player_homing_bullet_light_2] = image_player_homing_bullet_light_2;
	image_entries[image_LUT_player_homing_bullet_shadow_0] = image_player_homing_bullet_shadow_0;
	image_entries[image_LUT_player_homing_bullet_shadow_1] = image_player_homing_bullet_shadow_1;
	image_entries[image_LUT_player_homing_bullet_shadow_2] = image_player_homing_bullet_shadow_2;
	image_entries[image_LUT_player_bullet_light] = image_player_bullet_light;
	image_entries[image_LUT_player_bullet_shadow] = image_player_bullet_shadow;
	image_entries[image_LUT_player_explosion_0] = image_player_explosion_0;
	image_entries[image_LUT_player_explosion_1] = image_player_explosion_1;
	image_entries[image_LUT_player_explosion_2] = image_player_explosion_2;
	image_entries[image_LUT_player_explosion_3] = image_player_explosion_3;
	image_entries[image_LUT_player_explosion_4] = image_player_explosion_4;
	image_entries[image_LUT_player_explosion_5] = image_player_explosion_5;
	image_entries[image_LUT_player_explosion_6] = image_player_explosion_6;
	image_entries[image_LUT_player_explosion_7] = image_player_explosion_7;
	image_entries[image_LUT_player_explosion_8] = image_player_explosion_8;
	image_entries[image_LUT_player_explosion_9] = image_player_explosion_9;
	image_entries[image_LUT_player_explosion_10] = image_player_explosion_10;
	image_entries[image_LUT_player_explosion_11] = image_player_explosion_11;
	image_entries[image_LUT_enemy_bullet_0_light] = image_enemy_bullet_0_light;
	image_entries[image_LUT_enemy_bullet_0_shadow] = image_enemy_bullet_0_shadow;
	image_entries[image_LUT_enemy_bullet_1_light] = image_enemy_bullet_1_light;
	image_entries[image_LUT_enemy_bullet_1_shadow] = image_enemy_bullet_1_shadow;
	image_entries[image_LUT_enemy_bullet_2_light] = image_enemy_bullet_2_light;
	image_entries[image_LUT_enemy_bullet_2_shadow] = image_enemy_bullet_2_shadow;
	image_entries[image_LUT_enemy_homing_bullet_light] = image_enemy_homing_bullet_light;
	image_entries[image_LUT_enemy_homing_bullet_shadow] = image_enemy_homing_bullet_shadow;
	image_entries[image_LUT_enemy_laser_light] = image_enemy_laser_light;
	image_entries[image_LUT_enemy_laser_shadow] = image_enemy_laser_shadow;
	image_entries[image_LUT_enemy_ship_0_light] = image_enemy_ship_0_light;
	image_entries[image_LUT_enemy_ship_0_shadow] = image_enemy_ship_0_shadow;
	image_entries[image_LUT_enemy_ship_1_light] = image_enemy_ship_1_light;
	image_entries[image_LUT_enemy_ship_1_shadow] = image_enemy_ship_1_shadow;
	image_entries[image_LUT_enemy_ship_2_light] = image_enemy_ship_2_light;
	image_entries[image_LUT_enemy_ship_2_shadow] = image_enemy_ship_2_shadow;
	image_entries[image_LUT_enemy_ship_3_light] = image_enemy_ship_3_light;
	image_entries[image_LUT_enemy_ship_3_shadow] = image_enemy_ship_3_shadow;
	image_entries[image_LUT_enemy_ship_4_light] = image_enemy_ship_4_light;
	image_entries[image_LUT_enemy_ship_4_shadow] = image_enemy_ship_4_shadow;
	image_entries[image_LUT_enemy_ship_4_lightball] = image_enemy_ship_4_lightball;
	image_entries[image_LUT_enemy_ship_4_shadowball] = image_enemy_ship_4_shadowball;
	image_entries[image_LUT_enemy_ship_5_light] = image_enemy_ship_5_light;
	image_entries[image_LUT_enemy_ship_5_shadow] = image_enemy_ship_5_shadow;
	image_entries[image_LUT_enemy_ship_6_light] = image_enemy_ship_6_light;
	image_entries[image_LUT_enemy_ship_6_shadow] = image_enemy_ship_6_shadow;
	image_entries[image_LUT_box_light_1] = image_box_light_1;
	image_entries[image_LUT_box_light_2] = image_box_light_2;
	image_entries[image_LUT_box_light_3] = image_box_light_3;
	image_entries[image_LUT_box_light_4] = image_box_light_4;
	image_entries[image_LUT_box_light_5] = image_box_light_5;
	image_entries[image_LUT_box_light_6] = image_box_light_6;
	image_entries[image_LUT_box_shadow_1] = image_box_shadow_1;
	image_entries[image_LUT_box_shadow_2] = image_box_shadow_2;
	image_entries[image_LUT_box_shadow_3] = image_box_shadow_3;
	image_entries[image_LUT_box_shadow_4] = image_box_shadow_4;
	image_entries[image_LUT_box_shadow_5] = image_box_shadow_5;
	image_entries[image_LUT_box_shadow_6] = image_box_shadow_6;
	image_entries[image_LUT_box_solid_1] = image_box_solid_1;
	image_entries[image_LUT_box_solid_2] = image_box_solid_2;
	image_entries[image_LUT_box_solid_3] = image_box_solid_3;
	image_entries[image_LUT_box_solid_4] = image_box_solid_4;
	image_entries[image_LUT_box_solid_5] = image_box_solid_5;
	image_entries[image_LUT_box_solid_6] = image_box_solid_6;
	image_entries[image_LUT_boss1_enemy_ship_light] = image_boss1_enemy_ship_light;
	image_entries[image_LUT_boss1_enemy_ship_shadow] = image_boss1_enemy_ship_shadow;
	image_entries[image_LUT_boss1_grenade_light] = image_boss1_grenade_light;
	image_entries[image_LUT_boss1_grenade_shadow] = image_boss1_grenade_shadow;
	image_entries[image_LUT_chain_hit_light] = image_chain_hit_light;
	image_entries[image_LUT_chain_hit_shadow] = image_chain_hit_shadow;
	image_entries[image_LUT_explosion_light_0] = image_explosion_light_0;
	image_entries[image_LUT_explosion_light_1] = image_explosion_light_1;
	image_entries[image_LUT_explosion_light_2] = image_explosion_light_2;
	image_entries[image_LUT_explosion_light_3] = image_explosion_light_3;
	image_entries[image_LUT_explosion_light_4] = image_explosion_light_4;
	image_entries[image_LUT_explosion_light_5] = image_explosion_light_5;
	image_entries[image_LUT_explosion_shadow_0] = image_explosion_shadow_0;
	image_entries[image_LUT_explosion_shadow_1] = image_explosion_shadow_1;
	image_entries[image_LUT_explosion_shadow_2] = image_explosion_shadow_2;
	image_entries[image_LUT_explosion_shadow_3] = image_explosion_shadow_3;
	image_entries[image_LUT_explosion_shadow_4] = image_explosion_shadow_4;
	image_entries[image_LUT_explosion_shadow_5] = image_explosion_shadow_5;
	image_entries[image_LUT_particle_light] = image_particle_light;
	image_entries[image_LUT_particle_shadow] = image_particle_shadow;
	image_entries[image_LUT_powerslot] = image_powerslot;
	image_entries[image_LUT_lives] = image_lives;
	image_entries[image_LUT_bossWarning] = image_bossWarning;
	image_entries[image_LUT_background0] = image_bg0;
	image_entries[image_LUT_titleScreen] = image_titleScreen;
	
	// Boss images
	bossImage_entries[bossImage_LUT_1_body] = bossImage_1_body;
	bossImage_entries[bossImage_LUT_1_leftarm_armed] = bossImage_1_leftarm_armed;
	bossImage_entries[bossImage_LUT_1_rightarm_armed1] = bossImage_1_rightarm_armed1;
	bossImage_entries[bossImage_LUT_1_rightarm_armed2] = bossImage_1_rightarm_armed2;
	bossImage_entries[bossImage_LUT_1_leftarm_nonarmed] = bossImage_1_leftarm_nonarmed;
	bossImage_entries[bossImage_LUT_1_rightarm_nonarmed] = bossImage_1_rightarm_nonarmed;
}

void freeGameLUTs()
{
	
}