#include "common.h"

int levelStream[] = {
	cmd_wait(256),
	// Chapter 1
	// Wave 1
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_1, LIGHT, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_1, LIGHT, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_1, LIGHT, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_1, LIGHT, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_1, LIGHT, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_1, LIGHT, 1),
	cmd_wait(256),
	cmd_newWave,
	// Wave 2
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_2, SHADOW, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_2, SHADOW, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_2, SHADOW, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_2, SHADOW, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_2, SHADOW, 1),
	cmd_wait(64),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_2, SHADOW, 1),
	cmd_wait(128),
	cmd_newWave,
	// Wave 3
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_3, LIGHT, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_3, LIGHT, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_3, LIGHT, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_3, LIGHT, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_3, LIGHT, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_3, LIGHT, 1),
	cmd_wait(128),
	cmd_newWave,
	// Wave 4
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_4, SHADOW, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_4, SHADOW, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_4, SHADOW, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_4, SHADOW, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_4, SHADOW, 1),
	cmd_wait(96),
	enemy(0, 0, 2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_4, SHADOW, 1),
	cmd_killed,
	cmd_newWave,
	// Wave 5
	enemy(55, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(85, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(115, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(145, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(175, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(205, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(235, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(265, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	cmd_wait(48),
	enemy(55, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(85, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(115, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(145, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(175, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(205, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(235, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(265, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	cmd_wait(48),
	enemy(55, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(85, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(115, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(145, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(175, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(205, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(235, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(265, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	cmd_wait(48),
	enemy(55, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(85, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(115, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(145, 0, 1, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, Pattern_1_5, LIGHT, 0),
	enemy(175, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(205, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(235, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	enemy(265, 0, 1, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_0_light, Pattern_1_5, SHADOW, 0),
	cmd_wait(48),
	cmd_killed,
	cmd_newWave,
	// Wave 6
	enemy(107, 20, 16, image_LUT_enemy_ship_2_light, image_LUT_enemy_bullet_1_light, Pattern_1_6, LIGHT, 1),
	enemy(214, 20, 16, image_LUT_enemy_ship_2_shadow, image_LUT_enemy_bullet_1_light, Pattern_1_6, SHADOW, 1),
	cmd_killed,
	cmd_newWave,
	// Test boss
	enemy(160, 60, 50, image_LUT_enemy_ship_3_light, image_LUT_enemy_bullet_0_light, Pattern_1_7, LIGHT, 1),
	cmd_killed,
	LVLSTR_END
	};
