#include "common.h"

int levelStream[] = {
	cmd_wait(256),
	// Chapter 1
	// Wave 1
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_0, LIGHT, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_0, LIGHT, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_0, LIGHT, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_0, LIGHT, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_0, LIGHT, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_0, LIGHT, 1),
	cmd_wait(256),
	cmd_newWave,
	// Wave 2
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_1, SHADOW, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_1, SHADOW, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_1, SHADOW, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_1, SHADOW, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_1, SHADOW, 1),
	cmd_wait(64),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_1, SHADOW, 1),
	cmd_wait(128),
	cmd_newWave,
	// Wave 3
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_2, LIGHT, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_2, LIGHT, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_2, LIGHT, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_2, LIGHT, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_2, LIGHT, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_1_light, callback_LUT_2, LIGHT, 1),
	cmd_wait(128),
	cmd_newWave,
	// Wave 4
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_3, SHADOW, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_3, SHADOW, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_3, SHADOW, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_3, SHADOW, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_3, SHADOW, 1),
	cmd_wait(96),
	enemy(2, image_LUT_enemy_ship_0_shadow, image_LUT_enemy_bullet_1_shadow, callback_LUT_3, SHADOW, 1),
	cmd_killed,
	
	// Test boss
	enemy(50, image_LUT_enemy_ship_0_light, image_LUT_enemy_bullet_0_light, callback_LUT_4, LIGHT, 0),
	cmd_killed,
	LVLSTR_END
	};
